import React, { lazy, Suspense } from 'react';
const MyDemo = lazy(() => import('./Demo'))

const DemoLazy = () => {
    return (
        <Suspense fallback={<div className='bg-danger border'>Loading...</div>}>

            <div>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/> <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
                <MyDemo/>
            </div>
        </Suspense>
    );
};

export default DemoLazy;